name: tests

variables:
  - group: unittest-samples

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: "ubuntu-20.04"

resources:
  repositories:
    - repository: PipelineTemplates
      type: github
      name: CybercentreCanada/assemblyline-pipeline-templates
      ref: refs/heads/multibuild_from_repo
      endpoint: github-repo-sa
      trigger: none
    - repository: unittest-samples
      type: github
      name: $(unittest_samples_repository)
      ref: main
      endpoint: github-repo-sa
      trigger: none

stages:
  # Test YARA service
  - template: stages/test-service.yaml@PipelineTemplates
    parameters:
      samples_repo: unittest-samples
      test_container: "true"
      dockerfile_path: ./yara_/Dockerfile
      service_name: YARA

  # Test TagCheck service
  - template: stages/test-service.yaml@PipelineTemplates
    parameters:
      samples_repo: unittest-samples
      test_container: "true"
      dockerfile_path: ./tagcheck/Dockerfile
      service_name: TagCheck
