name: build

trigger:
  tags:
    include: ["v*"]
pr: none

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: deploy
    jobs:
      - job: deploy
        displayName: Deploy containers to dockerhub
        variables:
          - group: deployment-information
        steps:
          - task: Docker@2
            displayName: Login to docker hub
            inputs:
              command: login
              containerRegistry: dockerhub
          - task: Docker@2
            displayName: Login to chimera
            inputs:
              command: login
              containerRegistry: CHIMERA-U-ACR
          - script: |
              set -xv  # Echo commands before they are run
              export TAG=${BUILD_SOURCEBRANCH#"refs/tags/v"}
              if [[ "$TAG" == *stable* ]]; then export BUILD_TYPE=stable; else export BUILD_TYPE=latest; fi
              export SERIES="`expr $TAG : '\([0-9]\+\.[0-9]\+\.\)'`${BUILD_TYPE}"

              docker build --build-arg version=$TAG --build-arg branch=$BUILD_TYPE -t cccs/assemblyline-service-yara:$TAG -t cccs/assemblyline-service-yara:$BUILD_TYPE -f ./yara_/Dockerfile .

              docker build --build-arg version=$TAG --build-arg build_type=$BUILD_TYPE -t cccs/assemblyline-service-tagcheck:$TAG -t cccs/assemblyline-service-tagcheck:$BUILD_TYPE -f ./tagcheck/Dockerfile .

              for SERVICE in "assemblyline-service-yara" "assemblyline-service-tagcheck"
              do
                for IMAGE in "cccs/" "uchimera.azurecr.io/cccs/"
                do
                  docker tag cccs/${SERVICE}:$BUILD_TYPE ${IMAGE}${SERVICE}:$TAG
                  docker tag cccs/${SERVICE}:$BUILD_TYPE ${IMAGE}${SERVICE}:$BUILD_TYPE
                  docker tag cccs/${SERVICE}:$BUILD_TYPE ${IMAGE}${SERVICE}:$SERIES
                  docker push ${IMAGE}${SERVICE} --all-tags
                done
              done
            displayName: Deploy to container repositories
